### ISSUE TITLE
v0.2.0 tracker

### ISSUE THREAD

**Issue by MichaelHirn** [MichaelHirn/authless#7]
- [x] add new `authless` endpoint `/findRoute`: to get which `service:accountType` is available
- [x] add new `authless` default handler
- [x] add new `authless` functionality to support more `/url` params to control handling and return results format
